name: machine_code
description: Generating machine codes of different lengths through hard drive's uuid and salt.
version: 0.0.8
homepage:
repository: https://github.com/CalsRanna/machine_code

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
